### ISSUE TITLE
Default value of NewsListingBlock

### ISSUE THREAD

**Issue by shylux** [4teamwork/ftw.news#58]
I set up a NewsListingBlock with `ftw.inflator`. After that i couldn't edit the block because the default value for `filter_by_path` was set to `None` which failed in `z3c/form/converter.py(308)`. It expects a missing value to be `[]` but it was set to `None`.

The current workaround is to specify the empty list in the inflator:
https://github.com/4teamwork/bern.web/blob/master/bern/web/profiles/examplecontent/content_creation/05_startpage.json#L171-L181

**Comment by shylux** [comment]
Fix in https://github.com/4teamwork/ftw.news/blob/52fed88a5baf22c3a05784ada8c5d4e791c97ff4/ftw/news/contents/common.py#L23-L37

**Comment by jone** [comment]
@shylux does that mean it is already fixed and we can close the issue?

**Comment by shylux** [comment]
Yes, is resolved.
